#  environment document

name: emgbinders
channels:
  - conda-forge
  - resurfemg
dependencies:
  - resurfemg
  - ipympl
  - ipywidgets=7.7.0
  - jupyter
  - matplotlib=3.3.3
  - notebook
  - numexpr=2.7.3
  - numpy
  - pandas
  - pyxdf





  